version: '3'

services:
    ratetask:
        build: .
        image: task:latest
        entrypoint: /bin/sh ./entrypoint.sh
        command: python manage.py runserver 0.0.0.0:8080

        volumes:
            - .:/app
        ports:
            - 8080:8080
        depends_on:
            - postgres
        env_file:
            - ./.env
    postgres:
        env_file:
            - ./.env
        build:
            context: .
            dockerfile: ./Dockerfile.db
        volumes:
            - ./rates.sql:/docker-entrypoint-initdb.d/rates.sql

    pgadmin:
        image: dpage/pgadmin4
        networks:
            - default
        depends_on:
            - postgres
        env_file:
            - ./.env
        ports:
            - 5050:5050

